# Generated by Django 4.1.2 on 2022-11-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'CPU'), (2, 'GPU')], default=1)),
                ('title', models.CharField(max_length=128)),
                ('machine_limit', models.PositiveSmallIntegerField()),
                ('pricing', models.DecimalField(decimal_places=10, max_digits=10)),
                ('priority', models.PositiveSmallIntegerField(max_length=2)),
                ('ghz', models.PositiveIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(max_length=2)),
                ('users', models.TextField(blank=True)),
                ('is_unlimited', models.BooleanField()),
                ('black_list', models.CharField(max_length=256)),
                ('is_active', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
