# Generated by Django 4.1.2 on 2022-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='per_second',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='pricing',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='priority',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='sort_order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
