# Generated by Django 4.1.2 on 2022-11-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_per_second_alter_package_pricing_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='package',
            table='package',
        ),
    ]
