# Generated by Django 4.1.2 on 2022-11-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_package_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='black_list',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='per_second',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='package',
            name='pricing',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
