# Generated by Django 4.1.2 on 2022-11-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_package_black_list_alter_package_per_second_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='black_list',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
