# Generated by Django 4.1.2 on 2022-12-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbalance',
            table='user_balance',
        ),
    ]
