# Generated by Django 4.1.2 on 2022-11-02 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Disable')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField(blank=True)),
                ('file', models.CharField(max_length=256)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Open'), (2, 'Close'), (3, 'Answered'), (4, 'Pending')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.ticketdepartment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('file', models.CharField(max_length=256)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.tickets')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
