# Generated by Django 4.1.2 on 2022-11-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketdepartment',
            options={'verbose_name': 'ticket_department'},
        ),
    ]
