# Generated by Django 4.1.2 on 2022-11-02 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_alter_ticketdepartment_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketDepartment',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='TicketReply',
            new_name='Reply',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelTable(
            name='tickets',
            table='tickets',
        ),
    ]
