# Generated by Django 4.1.2 on 2022-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_rename_tickets_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(choices=[(1, 'Active'), (2, 'Disable')], default=1),
        ),
    ]
