# Generated by Django 4.1.2 on 2022-11-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_department_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(choices=[(1, 'Active'), (0, 'Disable')], default=1),
        ),
    ]
