# Generated by Django 4.1.2 on 2022-11-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_department_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
