# Generated by Django 4.1.2 on 2022-11-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_ticket_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='department_id',
            new_name='department',
        ),
    ]
