# Generated by Django 4.1.2 on 2022-11-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_rename_department_id_ticket_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user_id',
            new_name='user',
        ),
    ]
